# Netlify configuration file
[build]
  # Directory where the build files will be stored
  base = "sparecare_portfolio"
  command = "ng build --configuration production"
  publish = "dist/browserf"

[[redirects]]
  # Redirect all requests to index.html for Angular routing
  from = "/*"
  to = "/index.html"
  status = 200
